# **EDA** - Exploratory Data Analysis

In [ ]:
# 1. preprocessing --
# handle null values, handle duplicate values, check for irrelevant values, check the columns datatype.

# 2. statistical functions -- all the different measures

# 3. visualisation -- find the patterns, correlation between the columns, outliers, various insights.

# 4. Hypothesis Testing -- inferential stats

# 5. Encoding , Scaling

# -- the process of making your data consistent, accurate, model ready

### **Dataset link** -- https://drive.google.com/file/d/1DAtwzzlpMGKg3ZCEVUwFliE4gHNjEbP_/view

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df  = pd.read_csv("/content/BBData (1).csv")

In [ ]:
# rows and columns in df

df.shape

(27555, 10)

In [ ]:
# name of all the columns
df.columns

Index(['index', 'product', 'category', 'sub_category', 'brand', 'sale_price',
       'market_price', 'type', 'rating', 'description'],
      dtype='object')

In [ ]:
# print first 7 rows
df.head(7)

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...
5,6,Germ - Removal Multipurpose Wipes,Cleaning & Household,All Purpose Cleaners,Nature Protect,169.0,199.0,Disinfectant Spray & Cleaners,3.3,Stay protected from contamination with Multipu...
6,7,Multani Mati,Beauty & Hygiene,Skin Care,Satinance,58.0,58.0,Face Care,3.6,Satinance multani matti is an excellent skin t...

In [ ]:
# what is the dataset about -- commodities, groceries, maybe from some supermarket, e-commerce website.

In [ ]:
# Drop the column Index as we do not need two different index values
df.drop(['index'], axis = 1, inplace = True)

In [ ]:
df.columns

Index(['product', 'category', 'sub_category', 'brand', 'sale_price',
       'market_price', 'type', 'rating', 'description'],
      dtype='object')

In [ ]:
# check the duplicated values

df.duplicated().sum()

np.int64(354)

In [ ]:
df.drop_duplicates(inplace = True)

In [ ]:
# check the null values

df.isnull().sum()

product            1
category           0
sub_category       0
brand              1
sale_price         0
market_price       0
type               0
rating          8463
description      113
dtype: int64

In [ ]:
# Handling null values

# fill them -- specific value, a calculated value, mean, median, mode, ffill, bfill
# drop them

In [ ]:
df = df.dropna(subset = ['product'])

In [ ]:
# drops the row which is having null value in product column

In [ ]:
df['brand'] = df['brand'].fillna("Unknown")

In [ ]:
# replace the null values in description col with any value of your choice

df['description'] = df['description'].fillna("Description not available")

In [ ]:
df.isnull().sum()

product            0
category           0
sub_category       0
brand              0
sale_price         0
market_price       0
type               0
rating          8463
description        0
dtype: int64

In [ ]:
# lambda -- a shorthand function

# def func_name(parameters):
#       operations
#       return

# 100 lines of codes -- 5 of three lines functions -- 15 more lines to the code
# we can do the task in 5 simple lines

# lambda arguments: expression
# lambda x,y: x+y

In [ ]:
square = lambda x: x**x

square(2)

4

In [ ]:
# create a lambda function which calculates the cuberoot of any number.
cube_root = lambda x:x**(1/3)

cube_root(125)

4.999999999999999

In [ ]:
df1 = pd.DataFrame(df.groupby(['brand', 'category','sub_category'])['rating'])

In [ ]:
df1.head()

,0,1
0,"(&Me, Beverages, Health Drink, Supplement)","17900 3.8 Name: rating, dtype: float64"
1,"(&Me, Beverages, Tea)","10169 4.8 13299 4.7 Name: rating, dtype:..."
2,"(&Stirred, Beverages, Energy & Soft Drinks)",1493 4.1 1984 4.1 4123 4.0 14295 ...
3,"(&Stirred, Gourmet & World Food, Drinks & Beve...",8975 NaN 17222 NaN 19279 NaN 23854 Na...
4,"(109°F, Beauty & Hygiene, Health & Medicine)","26142 3.2 Name: rating, dtype: float64"

In [ ]:
df1.iloc[11,1]

2536     3.8
13546    3.5
14073    4.0
22274    NaN
Name: rating, dtype: float64

In [ ]:
df1.iloc[3,1]

8975    NaN
17222   NaN
19279   NaN
23854   NaN
26488   NaN
Name: rating, dtype: float64

In [ ]:
df['rating'] = df.groupby(['brand', 'category','sub_category'])['rating'].transform(lambda x: x.fillna(x.mean()))

In [ ]:
df.isnull().sum()

product            0
category           0
sub_category       0
brand              0
sale_price         0
market_price       0
type               0
rating          3562
description        0
dtype: int64

In [ ]:
df['rating'] = df.groupby(['brand'])['rating'].transform(lambda x: x.fillna(x.mean()))

In [ ]:
df.isnull().sum()

product            0
category           0
sub_category       0
brand              0
sale_price         0
market_price       0
type               0
rating          1598
description        0
dtype: int64

In [ ]:
df['rating'] = df['rating'].fillna(df['rating'].mean())

In [ ]:
df.isnull().sum()

product         0
category        0
sub_category    0
brand           0
sale_price      0
market_price    0
type            0
rating          0
description     0
dtype: int64

In [ ]:
df.shape

(27200, 9)

In [ ]:
# most of the products are of which category?

df['category'].value_counts().head(1)

category
Beauty & Hygiene    7683
Name: count, dtype: int64

In [ ]:
df['brand'].value_counts().head(1)

brand
Fresho    638
Name: count, dtype: int64

In [ ]:
df.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...

In [ ]:
# create a discount column

df['discount'] = df['market_price'] - df['sale_price']

In [ ]:
df.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description,discount
0,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...,0.0
1,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ...",0.0
2,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m...",131.0
3,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...,27.0
4,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...,0.0

In [ ]:
df.to_csv("Cleaned_file.csv")